### ISSUE TITLE
TypeError: Cannot read property 'generateMnemonic' of undefined

### ISSUE THREAD

**Issue by inDemniFi** [LtbLightning/bdk-rn#65]
I've downloaded this repository and have the wallet running locally however I am getting the errors below when I try to generate a mnemonic key:

 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'generateMnemonic' of undefined
TypeError: Cannot read property 'generateMnemonic' of undefined

The repository for the code here that produces the error above is: https://github.com/inDemniFi/BitcoinWallet

Separately, I have also followed the instructions here on the website, https://bitcoindevkit.org/tutorials/exploring_bdk_rn/, and successfully have the wallet installed locally and loading on my phone, however I am getting the same error above. 

Here is the entire error message:

 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'generateMnemonic' of undefined
TypeError: Cannot read property 'generateMnemonic' of undefined
    at ?anon_0_ (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:4314:74)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:4493:26)
    at _next (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:4512:29)
    at anonymous (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:4517:14)
    at tryCallTwo (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:4509:25)
    at apply (native)
    at getMnemonic (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:4323:26)
    at _performTransitionSideEffects (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:66144:22)
    at _receiveSignal (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:66094:45)
    at onResponderRelease (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:65950:34)
    at apply (native)
    at invokeGuardedCallbackProd (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:82494:21)
    at apply (native)
    at invokeGuardedCallback (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:82670:42)
    at apply (native)
    at invokeGuardedCallbackAndCatchFirstError (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:82684:36)
    at executeDispatch (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:82761:48)
    at executeDispatchesInOrder (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:82783:26)
    at executeDispatchesAndRelease (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:84556:35)
    at executeDispatchesAndReleaseTopLevel (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:84563:43)
    at forEach (native)
    at forEachAccumulated (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:83377:22)
    at runEventsInBatch (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:84576:27)
    at runExtractedPluginEventsInBatch (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:84686:25)
    at anonymous (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:84657:42)
    at batchedUpdates$1 (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:98122:20)
    at batchedUpdates (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:84532:36)
    at _receiveRootNodeIDEvent (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:84656:23)
    at receiveTouches (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:84745:34)
    at apply (native)
    at __callFunction (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:6714:36)
    at anonymous (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:6434:31)
    at __guard (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:6651:15)
    at callFunctionReturnFlushedQueue (http://192.168.1.107:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:6433:21)

**Comment by Czino** [comment]
I see your repo still refers to version 0.1.1. `bdk-rn` is at version 0.29.0 now.

**Comment by inDemniFi** [comment]
Resolved by Bitcoin Zavior.
